### ISSUE TITLE
Omics Visualizer not retrieving STRING network

### ISSUE THREAD

**Issue by dorvashmr** [marclegeay/omics-visualizer#8] opened 2022-08-30 07:34 UTC
Hi,
I recently installed the Cytoscape and omics visualizer. I faced a problem, however.
when I wanted to go through with the examples provided on omics visualizer website, after importing and filtering the dataset for the first example, the network cannot be retrieved by SRTINGapp as it does not provide any option for the "Species" to be selected and it prints the following error in task history:
 Task (STRING "list species" command) title: Retrieving list species from STRING
 Exception processing tunables
 Exception executing task: Error processing arguments: null

Could you please help we with this?

Cheers,
Reza

**Comment by scaramonche** [comment] 2022-08-30 07:46
Hi Reza, 
Thanks for reporting this issue. We are aware of it and working on a fix, but it will take a few more days before we can release a new version. In the meantime, you can create the STRING network using stringApp and then connect the network to the OV table from OV. In detail, you can do the following: 

1) Load the OV table as you would normally do, including filtering, etc.
2) Open the same table you loaded using Excel or a similar program, redo the filtering if needed and copy the identifiers you want to use to create a STRING network. Then, go back to Cytoscape and choose the menu "File -> Import -> Network from public databases". In the import dialog, choose "STRING: protein query" as the Data Source and paste the list of identifiers into the "Enter protein names or identifiers" field. Click Import.
3) Once you have the STRING network, go back the OV table, choose the forth icon (a connecting symbol) which will allow you to connect the network to the OV table. Then you choose the collection of your network, by default it should be called STRING network. You leave the next option as it is (set to "query term") and in the last line, you choose the name of the column that contains your identifiers (in my case "UniProt").

I will let you know as soon as there is a fix. 
Best wishes, 
Nadya

![Screen Shot 2022-08-17 at 7 26 33 PM](https://user-images.githubusercontent.com/4655368/187379233-7b7770a6-4323-4923-af6f-2e7a39deacf5.png)

**Comment by dorvashmr** [comment] 2022-09-01 04:45
Hi Nadya,
The way you described worked. Thank you for the instructions.

Cheers,
Reza

**Comment by scaramonche** [comment] 2023-08-23 22:53
This was caused by a bug in stringApp and has been fixed since version 2.0.1 of stringApp (released in January 2023).

**Closed as completed by scaramonche** 2023-08-23 22:53 UTC
